### ISSUE TITLE
Suggestion: additional (ahistorical) ignitions for V+E class engines

### ISSUE THREAD

**Issue by SillySMS** [ec429/SPEngine#10]
Hello,

1) If your intent is to stay very historical with as little speculation as possible, feel free to close this. You might also put a note in the readme indicating what balance of historical/speculative you're aiming for.

2) The V/E classes are, so far as I can tell, intended to be large upper-stage engines. Historically in the 1960s-1970s, America was nuts about hydrolox and the Soviets were nuts about staged combustion, so there was less interest in developing large open-cycle kerolox/hypergolic engines. For giggles, though, in my current career I'm staying away from good ideas like staged combustion and hydrolox, which opens up a gap for "large restartable vacuum engine"

3) By late 1967, the Saturn V was in operation, and I would suspect hypergols would be substantially simpler to ignite. I'm unsure about kerolox, but I suspect that would be similar.

As such, I would suggest adding the option for at least a few additional ignitions to at least the 4'th-and-onwards E-class engine (1970 rocketry node). With the V-class, it's a bit trickier; the 4'th config is a 1965 config, and the 5'th is a 1998 config. Either there'd be added ignitions before I can prove that reigniting large engines was possible, or there'd need to be a new, wholly speculative/extrapolated level put in between.

**Comment by ec429** [comment]
> or there'd need to be a new, wholly speculative/extrapolated level put in between.

FWIW all the V-class configs between the first one and the Merlin are speculative/extrapolated, including the one based on AJ-9-Kero (which is in RO, but marked as speculative there).

Also there's a bunch of other speculative configs in SPE already such as most of the W/X peroxides and Q throttleable-RL10s (though at least the latter have _some_ references to reality).  Basically I try to only go speculative when there's an Obvious Gap in history with real points at both ends to interpolate between.  Just in case anyone is looking at this in the future wondering what my policy is :wink:

**Comment by ec429** [comment]
Fixed by #11.
