### ISSUE TITLE
config files for lowercase families clash with uppercase files on Windows

### ISSUE THREAD

**Issue by todi** [ec429/SPEngine#12]
The Windows files-API is case-insensitive by default, so the files a.cfg/A.cfg, n.cfg/N.cfg, and y.cfg/Y.cfg can not coexist in the same folder there.

**Comment by chippydip** [comment]
I fixed this for myself locally and opened a PR in case anyone else wants to use those changes. I'm not sure if this is the *best* way to fix this, but it was the easiest way for me to just update configs: https://github.com/ec429/SPEngine/pull/15
