### ISSUE TITLE
Previously Tooled Configuration Does Not Provide Thrust When Used On New Vessel

### ISSUE THREAD

**Issue by damianreds** [ec429/SPEngine#13]
Hi! Not quite sure this is the place/way to report this, but I did not find a KSP forum thread.

I have recently started a new KSP 1.6.1 RO+RP-1 career game and encountered the following when creating my first configs (ingame) for the first B-class engines.
Whenever I save a configuration by naming it and only if I tool it afterwards, the engine does not produce any thrust when said configuration is used on a new ship/vessel.  First time works like a charm, but cannot make it work on new vessels.

Manual workaround found is two-fold: a) avoid tooling the configuration, or b) deleting tooled configuration and creating a new one (every time)

Hopefully this works - happy to provide more information if needed.

**Comment by damianreds** [comment]
Forgot to confirm the engine consumes resources while on the launchpad, however no thrust effects visible as vessel is stationary.

**Comment by damianreds** [comment]
Closed due to User Error.

**Comment by ec429** [comment]
Hi, if you can describe what you turned out to be doing wrong, in case anyone in the future has the same problem, that would be useful.

> did not find a KSP forum thread

FYI there's one [here](https://forum.kerbalspaceprogram.com/index.php?/topic/181186-161-simple-procedural-engines/).
