### ISSUE TITLE
R-Class overpowered` ? 

### ISSUE THREAD

**Issue by glilienthal** [ec429/SPEngine#18]
The RL-10-A-1 or RL10-A-3-3 have only 67kN in RO. However, in SPE they have 100kN.
Why? 
Maybe typo? 

Shall I do PR?

**Comment by ec429** [comment]
Working as designed.

I suppose I should give more explanation than that, so here goes... every class of engine in SPE has a thrust range, with the real-life engine it's based off being usually around 60-80% of the maximum.  You pick a thrust in the range (for the R-class TL1 that's 30-100kN), and your mass and cost get scaled accordingly (with exponents of 0.8 and 1.2 respectively, so bigger engines have slightly better TWR but are slightly more expensive per kN of thrust).

So if you make a 100kN R-class, you're getting an expensive engine (2100 funds, as compared to 1300 for the RL10-A-1), but one that's lighter (200kg) than (say) a pair of 50kN engines (230kg, but cheaper at 1828 funds).

**Comment by glilienthal** [comment]
Ah. Good to know. Thank you.
