### ISSUE TITLE
KSP 1.8.1, K-Class Engines have no plume or audio

### ISSUE THREAD

**Issue by jwvanderbeck** [ec429/SPEngine#19]
Honestly, I can't figure this one out so I'm punting.  Best I can tell the plume config in the MM Cache is the same as the one on the bespoke LR89 part, but the K-Class (either model) has no plume, or audio effects in the game under KSP 1.8.1.  IIRC it worked properly in 1.7.3 but I can't be 100% certain of that recollection.

**Comment by ec429** [comment]
The RealPlume configs of the engines SPE clones were changed in 1.8.1, causing this.  Some users have reported that removing the `PowerEffectName` setting from all the SPE part configs fixes this issue, but I haven't tested it myself.

**Comment by ec429** [comment]
Fixed by #22 (thanks @vader111).
