### ISSUE TITLE
KSP 1.8.1, H-Class Engines have no Plume or Audio

### ISSUE THREAD

**Issue by damianreds** [ec429/SPEngine#21]
Similar to #19, H-Class Engines do not show plume nor audio under KSP 1.8.1 & Real Plume 13.3.1.
Plume & Audio worked correctly under KSP 1.7.3.
Solution proposed for #19 is not applicable as there is no PowerEffectName setting on the H-Class Engines' config.
I tried adding `%powerEffectName = Hydrolox-Lower` but it didn't work.

**Comment by ec429** [comment]
Fixed by #22.
