### ISSUE TITLE
The mod only lets me unlock upgrades that do nothing and that´s it.

### ISSUE THREAD

**Issue by CarlosAM8** [ec429/SPEngine#27]
When I click on the SPEngine menu while it does open and show me the families and I can click on those it only shows a menu where you can unlock engine specifications like more thrust (and even when unlocked those do not actually apply to the engine), and that´s it, nothing when it comes to configuring or making engines yourself, only unlocking levels. Is the mod broken for me or is the whole "make engines yourself" and "modify thrust" stuff just an exaggeration?

![image](https://user-images.githubusercontent.com/71398068/93367983-e1d2a680-f812-11ea-836b-be79e2a557ed.png)

**Comment by ec429** [comment]
The way to create engines is to place one of the parts (e.g. for the family you have selected there, there should be a part called "H-class Procedural Engine"), and then use 'Configure' from the part's right-click menu.

If you don't have those parts, it could mean you're missing some of the dependencies — ROEngines is recommended (and provides a complete set of part models); alternatively RealEngines provides an H-class (as per the readme).

Also, the parts are unlocked by the same tech that unlocks their first config.  So e.g. in a new career game, the only ones available will be the A-class, a-class and B-class.  (The H-class is a pretty high tech engine, that requires the 1976 Hydrolox Engines tech.)

**Comment by ec429** [comment]
No further response from reporter; assuming user error, closing.
