### ISSUE TITLE
Do you plan for an update for 1.12.x versions of the game?

### ISSUE THREAD

**Issue by harrytherocketeer** [ec429/SPEngine#29]

**Comment by ec429** [comment]
When the RO/RP-1 suite of mods generally starts being released for 1.12.x (which I believe is coming Soon™) I will look into this.

(Have you tried the mod on 1.12, btw?  Some previous KSP updates have continued to work with old versions of the mod, not even needing a recompile.  If that's not the case here, a description of what breaks / error messages etc. would be helpful.)

**Comment by ec429** [comment]
As of version 0.4.0 (actually 0.3.2, but I never made a github Release for that), SPE targets KSP 1.12.2.
